### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO-526-S24/project-01-InsightSquad#4]
Dear Insight Squad: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |     2.5   |
| Proposal | 5         |   3.5     |
| Workflow | 1         |  0.5      |
| Teamwork | 1         |    1    |
| Total    | 10        |   7.5     |

**Overall**:
The Analysis Plan was too vague, and cost you the most points. 
From the peer-reviews:
> However, it will be better to add introduction, approach and discussion section.
- I don't see this addressed, and I agree. 

**Additionally**: 
1. On the `Data`, you should also have column types for the countries dataset. 
2. There should be some sort of timeline for completion, showing roughly when each step would be completed.

**Comment by Gchism94** [comment]
If you would like a regrade, please address and resubmit your proposal by **Monday, Feb 19th, 11:59pm**.

**Procedure**

1. Close this issue.
2. Open a new blank one requesting a regrade

Your final score will be the midpoint between the two scores.

**Comment by mfarmani95** [comment]
Thanks for the comments,
We will address them.
